name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      Name:
        description: input the name
        required: true
        default: fhaingue
  schedule:
    - cron: "*/15 6 6 * *"
jobs:
  echo-step:
    runs-on: ubuntu-lates
    steps:
      - run: echo "hello ${{ inputs.name }}"
  build:
    runs-on: ubuntu-lates
    steps:
      - run: |
          echo "${{ github.event_name }}"
          echo "${{ github.ref }}"

      - uses: actions/checkout@v3.3.0
      
      - name: List files
        run: |
          echo "the repo ${{ github.repository }}:"
          tree
    
